MovieManager.Web/Pages/CategoryDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieManager.Core.Contracts;
using MovieManager.Core.Entities;

namespace MovieManager.Web.Pages
{
    public class CategoryDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Movie[] MovieItems { get; private set; }


        public CategoryDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet(int id)
        {
            ViewData["Message"] = _unitOfWork.CategoryRepository.GetCategoryById(id).CategoryName;
            MovieItems = _unitOfWork.MovieRepository.GetMoviesByCategoryId(id).ToArray();
        }
    }
}

MovieManager.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieManager.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MovieManager.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieManager.Web.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MovieManager.Web/Pages/OverView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieManager.Core.Contracts;
using MovieManager.Core.DataTransferObjects;

namespace MovieManager.Web.Pages
{
    public class OverViewModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryForOverViewDTO[] CategoryItems { get; private set; }


        public OverViewModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet()
        {
            ViewData["Message"] = "Welcome to our streaming service";
            CategoryItems = _unitOfWork.CategoryRepository.GetCategoryForOverViewDTOs().ToArray();
        }
        public IActionResult OnPostCategorySelected(int categoryId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("/CategoryDetails", new { id = categoryId });
        }
    }
}

MovieManager.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieManager.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MovieManager.Web/Pages/CategoryDetails.cshtml
@page
@model MovieManager.Web.Pages.CategoryDetailsModel
@{
    ViewData["Title"] = "CategoryDetails";
}

<h1>CategoryDetails</h1>

<h2>@ViewData["Message"]</h2>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.MovieItems[0].Title)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.MovieItems[0].Duration)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.MovieItems[0].Year)
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MovieItems)
            {
            <tr>
                <td>
                    @Html.DisplayFor(_ => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(_ => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(_ => item.Year)
                </td>
            </tr>
            }
        </tbody>
    </table>
</form>
<form method="get">
    <button type ="Submit" class="btn btn-primary"
            asp-page="./OverView"> Back to OverView
    </button>
</form>

MovieManager.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieManager.Web/Pages/OverView.cshtml
@page
@model MovieManager.Web.Pages.OverViewModel
@{
    ViewData["Title"] = "OverView";
}

<h1>OverView</h1>

<h2>@ViewData["Message"]</h2>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryItems[0].CategoryName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryItems[0].Count)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryItems[0].AVGDuration)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CategoryItems)
            {
            <tr>
                <td>
                    @Html.DisplayFor(_ => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(_ => item.Count)
                </td>
                <td>
                    @Html.DisplayFor(_ => item.AVGDuration)
                </td>
                <td>
                    <button type="Submit"
                            class="btn btn-primary"
                            asp-page-handler="CategorySelected"
                            asp-route-categoryId="@item.Id">Select
                    </button>
                </td>
            </tr>
            }
        </tbody>
    </table>
</form>

MovieManager.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieManager.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MovieManager.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MovieManager.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>